version: '3'

services:
  
  captivefire:
    build:
      context: '.'
      args: 
        FOLDER: /app/
    image: captivefire:lua-lapis-2.0.0
    # ------- Docker Swarm compatibility -----------------
    # Using these directives for 'deploy' 
    # We need to run 'docker-compose --compatibility up -d'
    # -----------------------------------------------------
    deploy:
      resources:
        limits:
          cpus: '${CPU_MHZ_LIMIT:-0.10}'
          memory: '${RAM_MEMORY_LIMIT:-32M}'
        reservations:
          memory: '${RAM_MEMORY_LIMIT:-32M}'
    # -----------------------------------------------------
    container_name: '${CONTAINER_NAME:-captivefire}'
    # ----------- Doesn't work using an init script -------
    # ----------- Its used /etc/rc.local instead ----------
    # command: /app/docker/start-container.sh 
    restart: always
    ports:
      # --------------- Luci SSH Tunnel ------------------
      # ssh -L127.0.0.1:8080:127.0.0.1:8080 root@localhost
      # --------------------------------------------------
      - '${APP_SSH_PORT:-22}:22' # SSH Connection
      - '${APP_HTTP_PORT:-80}:80' # HTTP Captivefire
      - '${APP_HTTPS_PORT:-443}:443' # HTTPS Captivefire
    volumes:
      - ./docker/entrypoint.sh:/etc/rc.local
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
