#!/bin/sh

set -ux

UHTTPD_CONFIG="/app/uhttpd"
BANNER_FILE="/app/banner"
RC_LOCAL_FILE="/app/rc.local"

# Check if rc.local file is in the app and it's an old rc.local
find "$RC_LOCAL_FILE" && ! grep captivefire /etc/rc.local && \
    mv $RC_LOCAL_FILE /etc/rc.local

# Check if exits a banner file
find "$BANNER_FILE" && \
    cat $BANNER_FILE >> /etc/banner && \
    rm $BANNER_FILE

# If not exists file uhttpd config so
# The file was moved before or
# The firmware is building
! find "$UHTTPD_CONFIG" && exit 0

# Check if binary its installed
! which captivefire && exit 0

# Added uhttpd configuration
mv $UHTTPD_CONFIG /etc/config/uhttpd


captivefire set_luci_configuration
captivefire set_ssh_access
captivefire set_captive_password
captivefire set_system_config
captivefire set_network_config
captivefire set_dhcp_range
captivefire set_captive_portal_firewall
captivefire set_captive_wireless
captivefire disable_luci
captivefire remove_certificates

service cron start

exit 0