#!/bin/sh

set -eux

UHTTPD_CONFIG="/app/uhttpd"

# If not exists file uhttpd config so its for create the firmware image
[ ! -f "$UHTTPD_CONFIG" ] && exit 0

# Check if binary its installed
if ! which captivefire; then exit 0 fi

# Added uhttpd configuration
mv $UHTTPD_CONFIG /etc/config/uhttpd

captivefire set_luci_configuration
captivefire set_ssh_access
captivefire set_captive_password
captivefire set_system_config
captivefire set_network_config
captivefire set_dhcp_range
captivefire set_captive_portal_firewall
captivefire set_captive_wireless
captivefire disable_luci
captivefire remove_certificates

service cron start

exit 0