#!/bin/sh

set -ux

PATH_FIRMWARE_BUILDER="/home/build/openwrt/build_dir/target-*/root-*"

# Check if is in relative path or absolute
if pwd | grep $PATH_FIRMWARE_BUILDER
then
    # If it is in firmware builder
    PREFIX="$(pwd)/"
else
    # If it is in system
    PREFIX="/"
fi

PATH_APP="$PREFIX""app"
PATH_ETC="$PREFIX""etc"
PATH_BIN="$PREFIX""usr/bin"

SRC_UHTTPD_CONFIG="$PATH_APP""/uhttpd"
DST_UHTTPD_CONFIG="$PATH_ETC""/config/uhttpd"

SRC_BANNER_FILE="$PATH_APP""/banner"
DST_BANNER_FILE="$PATH_ETC""/banner"

SRC_RC_LOCAL_FILE="$PATH_APP""/rc.local"
DST_RC_LOCAL_FILE="$PATH_ETC""/rc.local"

BIN_CAPTIVEFIRE="$PATH_BIN""/captivefire"
BIN_CRON_SERVICE="$PATH_ETC""/init.d/cron"

# Check if exits a banner file
find "$SRC_BANNER_FILE" && \
    cat $SRC_BANNER_FILE >> $DST_BANNER_FILE && \
    rm $SRC_BANNER_FILE

find "$SRC_RC_LOCAL_FILE" && \
    mv $SRC_RC_LOCAL_FILE $DST_RC_LOCAL_FILE && \
    rm $SRC_RC_LOCAL_FILE

if pwd | grep $PATH_FIRMWARE_BUILDER
then
    # If it is in firmware builder
    exit 0
fi


# If not exists file uhttpd config so
# The file was moved before or
# The firmware is building
! find "$SRC_UHTTPD_CONFIG" && exit 0

# Check if binary its installed
! find "$BIN_CAPTIVEFIRE" && exit 0

# Added uhttpd configuration
mv $SRC_UHTTPD_CONFIG $DST_UHTTPD_CONFIG

$BIN_CAPTIVEFIRE set_luci_configuration
$BIN_CAPTIVEFIRE set_ssh_access
$BIN_CAPTIVEFIRE set_captive_password
$BIN_CAPTIVEFIRE set_network_config
$BIN_CAPTIVEFIRE set_dhcp_range
$BIN_CAPTIVEFIRE set_captive_portal_firewall
$BIN_CAPTIVEFIRE set_captive_wireless
$BIN_CAPTIVEFIRE disable_luci
$BIN_CAPTIVEFIRE remove_certificates
$BIN_CAPTIVEFIRE set_system_config

$BIN_CRON_SERVICE start

exit 0